site_name: PostMyRustache
repo_url: https://github.com/mikeshootzz/PostMyRustache
repo_name: PostMyRustache
site_url: https://postmyrustache.dev
theme:
  features:
    - navigation.tabs
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: material/github
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: slate
      primary: orange
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

    - scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
